CREATE TABLE IF NOT EXISTS orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    customer_id INTEGER,
    order_amount REAL NOT NULL,
    coupon_discount_amount REAL DEFAULT 0,
    coupon_discount_title TEXT,
    payment_status TEXT DEFAULT 'pending',
    order_status TEXT DEFAULT 'pending',
    total_tax_amount REAL DEFAULT 0,
    payment_method TEXT,
    delivery_address_id INTEGER,
    coupon_code TEXT,
    order_note TEXT,
    order_type TEXT DEFAULT 'dine_in',
    restaurant_id INTEGER NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME,
    delivery_charge REAL DEFAULT 0,
    schedule_at DATETIME,
    callback TEXT,
    otp TEXT,
    pending_date DATETIME,
    accepted_date DATETIME,
    confirmed_date DATETIME,
    processing_date DATETIME,
    handover_date DATETIME,
    picked_up_date DATETIME,
    delivered_date DATETIME,
    canceled_date DATETIME,
    cooked_date DATETIME,
    done_date DATETIME,
    refund_requested_date DATETIME,
    refunded BOOLEAN DEFAULT 0,
    delivery_address TEXT,
    delivery_ecode TEXT,
    scheduled BOOLEAN DEFAULT 0,
    discount_amount REAL DEFAULT 0,
    original_delivery_charge REAL DEFAULT 0,
    failed BOOLEAN DEFAULT 0,
    refund_request_canceled BOOLEAN DEFAULT 0,
    cancellation_reason TEXT,
    canceled_by INTEGER,
    tax_status TEXT DEFAULT 'pending',
    coupon_created_by INTEGER,
    distance REAL DEFAULT 0,
    cancellation_note TEXT,
    tax_percentage REAL DEFAULT 0,
    delivery_instruction TEXT,
    unavailable_item_note TEXT,
    additional_charge REAL DEFAULT 0,
    partially_paid_amount REAL DEFAULT 0,
    order_proof TEXT,
    cash_back_id INTEGER,
    extra_packaging_amount REAL DEFAULT 0,
    table_details TEXT,
    isdeleted BOOLEAN DEFAULT 0,
    issyncronized BOOLEAN DEFAULT 0,
    ready_date DATETIME,
    draft_name TEXT,
    isreported BOOLEAN DEFAULT 0,
    ontheway DATETIME,
    waiter TEXT,
    order_number TEXT,
    placed_at DATETIME,
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (delivery_address_id) REFERENCES addresses(id),
    FOREIGN KEY (restaurant_id) REFERENCES hotel(id),
    FOREIGN KEY (canceled_by) REFERENCES employee(id),
    FOREIGN KEY (coupon_created_by) REFERENCES employee(id)
); 