CREATE TABLE IF NOT EXISTS hotel (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT,
    phone TEXT,
    email TEXT,
    logo TEXT,
    latitude REAL,
    longitude REAL,
    address TEXT,
    footer_text TEXT,
    minimum_order NUMERIC,
    comission NUMERIC,
    schedule_order BOOLEAN,
    opening_time TEXT,
    closeing_time TEXT,
    status INTEGER,
    vendor_id INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME,
    free_delivery BOOLEAN,
    rating REAL,
    cover_photo TEXT,
    delivery BOOLEAN,
    take_away BOOLEAN,
    food_section BOOLEAN,
    tax NUMERIC,
    zone_id INTEGER,
    reviews_section BOOLEAN,
    active BOOLEAN,
    off_day TEXT,
    gst TEXT,
    self_delivery_system BOOLEAN,
    pos_system BOOLEAN,
    minimum_shipping_charge NUMERIC,
    delivery_time TEXT,
    veg BOOLEAN,
    non_veg BOOLEAN,
    order_count INTEGER,
    total_order INTEGER,
    per_km_shipping_charge NUMERIC,
    restaurant_model TEXT,
    maximum_shipping_charge NUMERIC,
    slug TEXT,
    order_subscription_active BOOLEAN,
    cutlery BOOLEAN,
    meta_title TEXT,
    meta_description TEXT,
    meta_image TEXT,
    announcement TEXT,
    announcement_message TEXT,
    qr_code TEXT,
    free_delivery_distance REAL,
    additional_data TEXT,
    additional_documents TEXT,
    package_id INTEGER,
    bgimg TEXT,
    icon TEXT,
    loyal_limit NUMERIC DEFAULT 0,
    isDelete BOOLEAN DEFAULT 0,
    isSyncronized BOOLEAN DEFAULT 0
);