// Fallback image data URIs to replace external placeholder services
// These are base64-encoded SVG images that work offline and don't require network requests
export const fallbackImages = {
  // 200x200 placeholder for food items
  food200: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDIwMCAyMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIiBmaWxsPSIjRjNGNEY2Ii8+CjxwYXRoIGQ9Ik0xMDAgNzBDMTE2LjU2OSA3MCAxMzAgODMuNDMxIDEzMCAxMDBDMTMwIDExNi41NjkgMTE2LjU2OSAxMzAgMTAwIDEzMEM4My40MzEgMTMwIDcwIDExNi41NjkgNzAgMTAwQzcwIDgzLjQzMSA4My40MzEgNzAgMTAwIDcwWiIgZmlsbD0iIzlDQTNBRiIvPgo8cGF0aCBkPSJNMTAwIDE0MEMxMTYuNTY5IDE0MCAxMzAgMTUzLjQzMSAxMzAgMTcwQzEzMCAxODYuNTY5IDExNi41NjkgMjAwIDEwMCAyMDBDODMuNDMxIDIwMCA3MCAxODYuNTY5IDcwIDE3MEM3MCAxNTMuNDMxIDgzLjQzMSAxNDAgMTAwIDE0MFoiIGZpbGw9IiM5Q0EzQUYiLz4KPC9zdmc+",
  
  // 40x40 placeholder for food thumbnails
  food40: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjQwIiBoZWlnaHQ9IjQwIiBmaWxsPSIjRjNGNEY2Ii8+Cjx0ZXh0IHg9IjIwIiB5PSIyNSIgZm9udC1mYW1pbHk9IkFyaWFsLCBzYW5zLXNlcmlmIiBmb250LXNpemU9IjE2IiBmaWxsPSIjOTlBM0FGIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBkeT0iLjNlbSI+8J+RrTwvdGV4dD4KPC9zdmc+",
  
  // 150x120 placeholder for order items
  order150x120: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTUwIiBoZWlnaHQ9IjEyMCIgdmlld0JveD0iMCAwIDE1MCAxMjAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxNTAiIGhlaWdodD0iMTIwIiBmaWxsPSIjRjNGNEY2Ii8+CjxwYXRoIGQ9Ik03NSA2MEM5MS41NjkgNjAgMTA1IDczLjQzMSAxMDUgOTBDMTA1IDEwNi41NjkgOTEuNTY5IDEyMCA3NSAxMjBDNTguNDMxIDEyMCA0NSAxMDYuNTY5IDQ1IDkwQzQ1IDczLjQzMSA1OC40MzEgNjAgNzUgNjBaIiBmaWxsPSIjOTlBM0FGIi8+CjxwYXRoIGQ9Ik03NSAxMDBDOTEuNTY5IDEwMCAxMDUgMTEzLjQzMSAxMDUgMTMwQzEwNSAxNDYuNTY5IDkxLjU2OSAxNjAgNzUgMTYwQzU4LjQzMSAxNjAgNDUgMTQ2LjU2OSA0NSAxMzBDNDUgMTEzLjQzMSA1OC40MzEgMTAwIDc1IDEwMFoiIGZpbGw9IiM5Q0EzQUYiLz4KPC9zdmc+",
  
  // Generic placeholder for any size
  generic: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjRjNGNEY2Ii8+Cjx0ZXh0IHg9IjUwIiB5PSI1NSIgZm9udC1mYW1pbHk9IkFyaWFsLCBzYW5zLXNlcmlmIiBmb250LXNpemU9IjEyIiBmaWxsPSIjOTlBM0FGIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBkeT0iLjNlbSI+SW1hZ2U8L3RleHQ+Cjwvc3ZnPg=="
};

// Helper function to get appropriate fallback image
export const getFallbackImage = (type = 'generic') => {
  return fallbackImages[type] || fallbackImages.generic;
};

// Helper function to handle image error
export const handleImageError = (event, fallbackType = 'generic') => {
  event.target.onerror = null; // Prevent infinite loop
  event.target.src = getFallbackImage(fallbackType);
}; 